"""The Codex/ChatGPT plugin — a shop window whose contents must not drift from the product.

The plugin ships the same skill `treg skill bootstrap` writes into `~/.codex/skills/`, generated by
`scripts/build_plugin.py`. A generated file that nobody checks is a copy, and a copy rots — so the
first test here is the one that matters: regenerate, and fail if the checked-in copy differs.

The rest guard the manifest, because it is read by a public directory rather than by us. A broken
path or an unsubstituted placeholder is invisible locally and embarrassing in a listing.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "plugin"
MANIFEST = PLUGIN / ".codex-plugin" / "plugin.json"
SKILL = PLUGIN / "skills" / "treg" / "SKILL.md"


@pytest.fixture(scope="module")
def manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def test_the_plugin_skill_is_not_stale():
    """`build_plugin.py --check` is the whole point: the served skill.md is the ONE source, and this
    is what notices when the plugin falls behind it."""
    r = subprocess.run([sys.executable, str(ROOT / "scripts" / "build_plugin.py"), "--check"],
                       capture_output=True, text=True)
    assert r.returncode == 0, (
        f"plugin SKILL.md is stale — regenerate with `python3 scripts/build_plugin.py`\n"
        f"{r.stdout}{r.stderr}")


def test_no_unsubstituted_placeholder_reaches_the_plugin():
    """`{BASE}` is substituted per-request by the SERVER. Nothing substitutes it inside an installed
    plugin, so shipping the literal would break every URL in the most-read page of the product."""
    text = SKILL.read_text(encoding="utf-8")
    assert "{BASE}" not in text
    assert "https://treg.superdesign.dev/install.sh" in text


def test_the_skill_maps_itself_onto_the_MCP_TOOLS(manifest):
    """The served skill is written around the `treg` command line — every other install path reaches
    treg that way. A plugin user has no terminal: they have the connector's tools. Without the
    mapping, the first run is an agent trying to run a shell command that does not exist."""
    text = SKILL.read_text(encoding="utf-8")
    for tool in ("catalog_search", "catalog_get", "call", "balance", "my_tools"):
        assert tool in text, f"the skill never mentions the {tool} tool"
    assert "TREG_TOKEN" in text            # what to do when the connector has no token yet
    assert manifest["mcpServers"] == "./.mcp.json"


def test_the_connector_points_at_production_over_https():
    """The listing is public. A plugin shipped pointing at a dev box or over http would work for
    exactly one person, and reviewers test from their own machines."""
    import json as _json
    mcp = _json.loads((PLUGIN / ".mcp.json").read_text(encoding="utf-8"))
    assert set(mcp) == {"treg"}
    url = mcp["treg"]["url"]
    assert url.startswith("https://"), url
    assert "ngrok" not in url and "localhost" not in url and "127.0.0.1" not in url
    assert mcp["treg"]["bearer_token_env_var"] == "TREG_TOKEN"


def test_category_and_capabilities_match_what_real_plugins_use(manifest):
    """These were guesses until I read OpenAI's own installed manifests under
    `~/.codex/plugins/cache/`: github is `Developer Tools` + ["Interactive", "Write"], gmail is
    `Communication`, openai-templates is `Productivity`. The published docs list neither set of
    allowed values, so the shipped plugins are the only real reference — and a store listing filed
    under an invented category is not a thing you get to quietly fix later."""
    iface = manifest["interface"]
    assert iface["category"] in {"Developer Tools", "Productivity", "Communication"}
    assert set(iface["capabilities"]) <= {"Interactive", "Write", "Read"}


def test_manifest_declares_what_the_directory_reads(manifest):
    for field in ("name", "version", "description", "skills", "interface"):
        assert manifest.get(field), f"plugin.json is missing `{field}`"
    iface = manifest["interface"]
    for field in ("displayName", "shortDescription", "longDescription", "category",
                  "composerIcon", "logo"):
        assert iface.get(field), f"plugin.json interface is missing `{field}`"


def test_every_declared_path_exists(manifest):
    """A path that resolves on the author's machine and nowhere else is the classic packaging bug."""
    paths = [manifest["skills"], manifest["interface"]["composerIcon"], manifest["interface"]["logo"]]
    paths += manifest["interface"].get("screenshots", [])
    for rel in paths:
        assert rel.startswith("./"), f"{rel} must be relative to the plugin root"
        assert (PLUGIN / rel[2:]).exists(), f"plugin.json points at {rel}, which does not exist"


def test_plugin_version_tracks_the_package():
    """One product, one version. A listing that claims 0.1.0 while the CLI is 0.7.0 is a support
    question waiting to happen."""
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    version = next(l.split('"')[1] for l in pyproject.splitlines() if l.startswith("version = "))
    assert json.loads(MANIFEST.read_text(encoding="utf-8"))["version"] == version


def test_the_listing_does_not_promise_routing(manifest):
    """The charter's standing rule: treg COMPARES providers, it does not route or fail over. The
    landing page already had to be corrected for this once — a store listing is harder to correct."""
    blob = json.dumps(manifest).lower()
    for claim in ("routes for you", "automatic failover", "fails over", "picks the best provider"):
        assert claim not in blob, f"listing copy claims {claim!r}, which treg does not do"
